name: Run Flask App with MongoDB

on:
  push:
    branches:
      - "development*"

jobs:
  run_app:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: --health-cmd "mongo --version"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run MongoDB and Flask app
        run: |
          mongod --fork --logpath /var/log/mongodb.log --dbpath /github/workspace/data/db
          python app.py