name: Run Flask App with MongoDB

on:
  push:
    branches:
      - "development*"

jobs:
  dev_app:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: --health-cmd "mongo --version"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run App test
        run: |
          python ./app.py &
          sleep 60  # Wait for the app to start
          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:5000/)
          if [ "$response_code" = "200" ]; then
            echo "App responded with 200 OK"
          else
            echo "App did not respond with 200 OK"
            exit 1  # Fail the workflow
          fi
          pkill -f app.py  # Stop the app