name: Create Azure Resource Group

on:
  push:
    branches:
      - "development*"  # Adjust this to your repository's main branch name

jobs:
  create-resource-group:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Generate Random String
      id: random-string
      run: echo "::set-output name=randomString::$(openssl rand -hex 6)"

    - name: Create Resource Group
      id: create-rg
      run: |
        rg_name="dccomics-${{ steps.random-string.outputs.randomString }}"
        az group create --name $rg_name --location "East US" --output none
        echo "::set-output name=resourceGroupName::$rg_name"

    - name: Set Resource Group Name as Environment Variable
      run: |
        echo "RESOURCE_GROUP_NAME=${{ steps.create-rg.outputs.resourceGroupName }}" >> $GITHUB_ENV