name: Create Resource Group

on:
  push:
    branches:
      - "development*"

permissions:
  id-token: write
  contents: read

jobs:
  create-resource-group:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: azure/login@v1
      name: Set up Azure CLI
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Generate random number
      id: random-number
      run: echo "::set-output name=random::$(shuf -i 10000-99999 -n 1)"

    - name: Create Resource Group
      id: create-rg
      run: |
        RG_NAME="dccomics${{ steps.random-number.outputs.random }}"
        az group create --name $RG_NAME --location eastus --output json

    - name: Display Resource Group Name
      run: |
        echo "Created Resource Group: ${{ steps.create-rg.outputs.RG_NAME }}"