
name: Deploy to Azure

on:
  push:
    branches:
      - "development"

permissions:
  id-token: write
  contents: read

jobs:
  delete-existing-resources:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Azure CLI
      - uses: azure/login@v1
        name: Set up Azure CLI
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Deploy Bicep Template
      - name: Deploy Bicep Template
        id: deploy-bicep-template
        run: |
          echo "Deploying Bicep template..."
          az deployment group create --resource-group dccomics --template-file ./deploy/dev.bicep --parameters location=eastus

      - name: Deploy Python Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: dccomics
          slot-name: production
          package: .
          platform: python
          version: '3.9'
          port: 5000
          startup-command: 'gunicorn --bind=0.0.0.0 --timeout 600 app:app'

      - name: Enable HTTPS
        run: |
            az webapp config set --resource-group my-resource-group --name dccomics-web-dev --https-only true