name: Build and deploy Python app to Azure Web App - dccomics-web-dev

env:
  MONGODB_SERVER_NAME: dccomics-mongodb-dev   # Replace with your Azure Cosmos DB name
  AZURE_WEBAPP_NAME: dccomics-web-dev  # Replace with your Azure Web App name

on:
  push:
    branches:
      - development
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy-bicep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep Template
        id: deploy-bicep-template
        run: |
          echo "Deploying Bicep template..."
          az deployment group create --resource-group dccomics --template-file ./deploy/dev.bicep --parameters location=eastus

  build:
    runs-on: ubuntu-latest
    needs: deploy-bicep

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

      - name: Get Cosmos DB connection string
        id: get-cosmosdb-connection-string
        run: |
          cosmos_db_connection_string=$(az cosmosdb keys list --name ${{ env.MONGODB_SERVER_NAME }} --resource-group dccomics --type connection-strings --query "connectionStrings[0].connectionString" --output tsv)
          echo "Cosmos DB connection string: $cosmos_db_connection_string"
          echo "::set-output name=mongodb_uri::$cosmos_db_connection_string"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, deploy-bicep]
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
        - name: Set up Azure CLI
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Download artifact from build job
          uses: actions/download-artifact@v2
          with:
           name: python-app
           path: .
          
        - name: 'Deploy to Azure Web App'
          uses: azure/webapps-deploy@v2
          id: deploy-to-webapp
          with:
           app-name: 'dccomics-web-dev'
           slot-name: 'production'
           publish-profile: ${{ secrets.AzureAppService_PublishProfile_e576a1f6c2aa4997b2a777665a8eac12 }}
          env:
           MONGODB_URI: ${{ steps.retrieve-mongodb-uri.outputs.mongodb_uri }}  # Use the retrieved MongoDB URI
