name: Deploy to Azure

on:
  push:
    branches:
      - "development"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-bicep-and-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: azure/login@v1
        name: Set up Azure CLI
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep Template
        id: deploy-bicep-template
        run: |
          echo "Deploying Bicep template..."
          az deployment group create --resource-group dccomics --template-file ./deploy/dev.bicep --parameters location=eastus

      - name: Get Cosmos DB connection string
        id: get-cosmosdb-connection-string
        run: |
          cosmos_db_connection_string=$(az cosmosdb keys list --name dccomics-mongodb-dev --resource-group dccomics --type connection-strings --query "connectionStrings[0].connectionString" --output tsv)
          echo "Cosmos DB connection string: $cosmos_db_connection_string"
          echo "::set-output name=connection_string::$cosmos_db_connection_string"
      
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy Python Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: dccomics-web-dev
          slot-name: production
          package: .
          platform: python
          version: '3.9'
          port: 8000
          startup-command: 'gunicorn --bind=0.0.0.0:8000 --timeout 600 app:app'
        env:
          MONGODB_URI: ${{ steps.get-cosmosdb-connection-string.outputs.connection_string }}