name: Azure Deployment

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy Bicep Template
        run: |
          az deployment group create --resource-group dccomics --template-file ./deploy/dev.bicep --verbose

      - name: Zip Flask App
        run: |
          zip -r app.zip app.py

      - name: Deploy Flask App using Zip Deploy
        run: |
          az webapp deployment source config-zip --name dccomics-web-dev --resource-group dccomics --src app.zip