name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: dccomics-web-dev  # Replace with your Azure Web App name
  PYTHON_VERSION: '3.9'               # Set your desired Python version

on:
  push:
    branches:
      - development  # Change to the appropriate branch

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Set up dependency caching for faster installs
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add a step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            .
            !venv/

  retrieve-mongodb-uri:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Cosmos DB connection string
        id: get-cosmosdb-connection-string
        run: |
          cosmos_db_connection_string=$(az cosmosdb keys list --name dccomics-mongodb-dev --resource-group dccomics --type connection-strings --query "connectionStrings[0].connectionString" --output tsv)
          echo "Cosmos DB connection string: $cosmos_db_connection_string"
          echo "::set-output name=mongodb_uri::$cosmos_db_connection_string"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, retrieve-mongodb-uri]

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .  # Deploy the current directory
          platform: python
          version: ${{ env.PYTHON_VERSION }}
          slot-name: production
          startup-command: 'gunicorn --bind=0.0.0.0:8000 --timeout 600 app:app'
        env:
          MONGODB_URI: ${{ steps.retrieve-mongodb-uri.outputs.mongodb_uri }}  # Use the retrieved MongoDB URI